### ISSUE TITLE
Help to intergation client pjsip ipv6

### ISSUE THREAD

**Issue by pnanh-github** [johanlantz/pj-nat64#3]
Hi johanlantz,
Many thanks for your code. But can you give me some instructions to integrate your code with my client pjsip to solve ipv6 problems.

Thanks for your help !

**Comment by johanlantz** [comment]
Hi Frank

I am on vacation and will be traveling until mid August. When I am back I
will see if I can improve the instructions a bit.

Our app is approved by Apple using this code since June but you may have to
do adaptations depending on your needs.

The code is a module so no patching needed. What I do right now is to check
on the onregstate2 callback if the servername is resolved to an IPv6
address i activate the module and ipv6media in pjmedia.

There are other things you may or may not have to manage depending on how
you treat connection changes etc.

Johan

**Comment by ivan-ushakov** [comment]
@johanlantz 

> The code is a module so no patching needed. What I do right now is to check
> on the onregstate2 callback if the servername is resolved to an IPv6
> address i activate the module and ipv6media in pjmedia.

I tried to follow this way but it get stuck inside PJ module registration code on mutex. Any ideas why?

**Comment by johanlantz** [comment]
Hi Ivan

I have updated the README.md with an example on how I do it.

**Comment by ivan-ushakov** [comment]
@johanlantz 

Thank you for answer. Looks like you current interface not ready for this approach (more over there is no `pj_nat64_set_options` function). I changed my local version but other people may be confused. So I think you need to update current interface.

**Comment by johanlantz** [comment]
Sorry about that, I had forgotten to upload some local changes I did before
vacations. Thanks for pointing it out, I have pushed them now

2016-08-22 19:48 GMT+02:00 Ivan notifications@github.com:
